AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to creates two IAM user groups, temporary password, and two IAM users.

Resources:
  NewUserTempPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: "Temporary password for new IAM users"
      GenerateSecretString:
        PasswordLength: 16
        RequireEachIncludedType: true

  EC2UserGroup:
      Type: 'AWS::IAM::Group'
      Properties:
        GroupName: EC2ReadOnlyGroup
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
          - "arn:aws:iam::aws:policy/IAMUserChangePassword"
          
  S3UserGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: S3ReadOnlyGroup
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/IAMUserChangePassword"

  EC2User:
    Type: 'AWS::IAM::User'
    DependsOn:
      - NewUserTempPassword
      - EC2UserGroup
    Properties:
      UserName: EC2User
      Groups:
        - !Ref EC2UserGroup
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:${NewUserTempPassword}}}"
        PasswordResetRequired: true

  S3User:
    Type: 'AWS::IAM::User'
    DependsOn:
        - NewUserTempPassword
        - S3UserGroup
    Properties:
      UserName: S3User
      Groups:
        - !Ref S3UserGroup
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:${NewUserTempPassword}}}"
        PasswordResetRequired: true
  
  S3User2:
    Type: 'AWS::IAM::User'
    DependsOn:
        - NewUserTempPassword
        - S3UserGroup
    Properties:
      UserName: S3User2
      Groups:
        - !Ref S3UserGroup
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:${NewUserTempPassword}}}"
        PasswordResetRequired: true